#OBJS specifies which files to compile as part of the project
OBJS = chrono.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = chrono.exe

#This is the target that compiles our executable
all : $(OBJS)
	clang++ $(OBJS) -g -w -lUser32 -o $(OBJ_NAME)
