[package]
name = "game"
version = "0.1.0"
authors = ["Leonardo Paffi <leonardopaffi@hotmail.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fermium = "20016.1.1"